name: Static Analysis

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  php-stan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: PHP Static Analysis
      run: composer stan
